<?php
use  Pachel\dbClass\dataModel;
/**
 * @generated by dbClass #datum
 * @author Tóth László
 * @email pachel82@gmail.com
**/
class generated_#tableModel extends dataModel{
	/**
	* @var string $_primary A(z) "#table" tábla elsődleges kulcsa az adatbázisban
	*/
	protected $_primary = "#primary";

	/**
	* @var string $_tablename Az SQL tábla neve
	*/
	protected $_tablename = "#table";

	/**
	* @var array $_not_visibles A SELECT lekérdezésben láthatatlan mezők nevei
	*/
	protected $_not_visibles = [];

	/**
	* @var bool $_safemode Biztonságos mód a törléshez, ha ez true, akkor a mezőt is be kell állítani
	*/
	protected $_safemode = false;

	/**
	* @var string $_safefield A törléshez használt mező, ami a biztonságos törlésnél 1-es értéket vesz fel
	*/
	protected $_safefield = "deleted";
	//Az adatmodel osztály neve
	protected $_modelclass = generated_#tableDataModel::class;
}
class generated_#tableDataModel{
#variables
}